---
apiVersion: v1
offerings:
  - name: testing-deploy-arch-ibm-core-security-svcs
    kind: solution
    catalog_id: f64499c8-eb50-4985-bf91-29f9e605a433
    offering_id: eacbc679-a7e1-41ea-b372-58362c8155e5
    variations:
      - name: standard
        mark_ready: false
        install_type: fullstack
        format_kind: stack
        validation_type: projects
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
